### ISSUE TITLE
When the newest version in github repo will be pushed to rubygems.org?

### ISSUE THREAD

**Issue by nanamiwang** [rubymotion/motion-support#25]
The version on rubygems.org was too old, released at Dec 28 2013
https://rubygems.org/gems/motion-support
At least this update is very useful:
rubymotion/motion-support#22
I encountered a file dependency issue recently, the root cause is that 'motion-yapper' gem set detect_dependencies to false for motion-support, but Promotion-menu gem can't work without auto dependency detection.

**Comment by colinta** [comment]
I'll push the most recent code up today, thanks for pointing that out!

**Comment by jbender** [comment]
@colinta Want to tag the latest as `0.3.0` and close the issue?

**Comment by colinta** [comment]
Good call - done!
